### ISSUE TITLE
Improve module for 2-1 laptop witch touchscreen

### ISSUE THREAD

**Issue by RemyL** [harshadgavali/gnome-gesture-improvements#8] opened 2021-08-17 11:47 UTC
Hi,

First thank you for your module that add nice modifications to gnome gesture.

I get few issues with my 2-1 laptop that has a touchscreen and act as a touchpad. I don't know if it will be possible to ass some improvement to your module to make it work without any issue with touchscreen.

Here is what i get:

- touchscreen act like the touchpad except that the 3 fingers gnome gesture are also applied when using 4 or 5 fingers.
- if i use your module (even if i use 3 or 4 fingers for your new gesture) it always want to maximize or minimize windows AND perform overview navigation at the same time  when i use 3, 4 or 5 fingers.
- swith windows doesn't work on touchscreen and it always switch workspace (with 3 or 4 fingers no matter the setting)

I hope that my explanations are ok and that it will be possible to work on this.

**Comment by harshadgavali** [comment] 2021-08-17 15:29
> if i use your module (even if i use 3 or 4 fingers for your new gesture) it always want to maximize or minimize windows AND perform overview navigation at the same time when i use 3, 4 or 5 fingers.

Can you try main branch to see if  9e2fec6d0de65bac311001ba4cc9cb900f69dbd3 fixes this ?
You'll get updates from gnome extension website, even if you installed from git.

**Comment by harshadgavali** [comment] 2021-08-17 15:35
Unfortunately I can't update other touchscreen gestures, as I don't have device to test them.
I don't want to modify any touchscreen gestures' behaviour yet.
If you see any other regressions, caused by this extensions, please report them here.

> swith windows doesn't work on touchscreen and it always switch workspace (with 3 or 4 fingers no matter the setting)

GNOME has/had different gesture for switching windows on touchscreen devices.
https://help.gnome.org/users/gnome-help/stable/touchscreen-gestures.html.en

> touchscreen act like the touchpad except that the 3 fingers gnome gesture are also applied when using 4 or 5 fingers.

You may want to report this at [gnome-shell](http://gitlab.gnome.org/GNOME/gnome-shell/).

**Comment by RemyL** [comment] 2021-08-18 09:42
I tried your modifications and i think that it's a good thing to disable touchscreen as you did.
Your extension only works for touchpad now and doesn't interfere with touchscreen so it's perfect.

Moreother it's good like that because gnome gesture for touchscreen are great and it's easy to move, maximize, minimize or change windows

**Comment by harshadgavali** [comment] 2021-08-30 15:50
Thanks for confirmation.
Closing this now.

**Closed by harshadgavali** 2021-08-30 15:50 UTC
Labels: touchscreen-gestures
