### ISSUE TITLE
Stop working features swipe to right or left 

### ISSUE THREAD

**Issue by Neo-29** [harshadgavali/gnome-gesture-improvements#144] opened 2022-11-18 17:45 UTC
You can´t swipe windows to left or right on desktop anymore
Gnome 43.1 Archlinux
The rest ( maximise ..etc) is ok

![image](https://user-images.githubusercontent.com/90937180/202769305-8f98b495-5297-48ab-8a3d-b06794f3bc8f.png)

this ( same with right )

**Comment by sidevesh** [comment] 2022-11-21 03:14
@Neo-29 is this issue similar to #141 ?
Seems like this is also a case of only horizontal gestures not working.

**Comment by Neo-29** [comment] 2022-11-21 10:33
No it's not.
Happens all the time

**Comment by harshadgavali** [comment] 2022-11-21 10:39
Hey @Neo-29,
I'm not able reproduce this issue yet.
Can you provide the output of `journalctl -f -o cat /usr/bin/gnome-shell`
### Steps to get output:
1. After you encounter issue
2. Run above command in terminal
3. Disable extension, and then enable extension again
4. Do 3 finger gestures
5. Share the output from terminal here

**Comment by HarshPatel5940** [comment] 2022-11-23 17:19
@harshadgavali i started having some problems with four finger swiping after todays update in fedora.

I am not sure, if i broke something. is there is any procedure to fix back this?

**Comment by harshadgavali** [comment] 2022-11-26 08:23
Closing this in favour of #141.

**Closed by harshadgavali** 2022-11-26 08:23 UTC

**Comment by Neo-29** [comment] 2022-11-26 10:26
Why did you close as completed?

**Comment by harshadgavali** [comment] 2022-11-26 10:30
@Neo-29, (TIL there are different ways to close github issue)

Sorry I meant to close this as duplicate of #141 .
Can you provide details I asked in that issue?

**Comment by Neo-29** [comment] 2022-11-26 10:34
> @Neo-29, (TIL there are different ways to close github issue)
> 
> Sorry I meant to close this as duplicate of #141 . Can you provide details I asked in that issue?

Can't.
No more with my laptop at the moment.

**Comment by Neo-29** [comment] 2022-12-12 19:59
Just to let you know
I reset gnome settings entirely
Working like a charm now
Really weird

**Comment by Neo-29** [comment] 2022-12-23 13:30
Stopped again working
after gtk4 and 3 update of today on arch

**Comment by Neo-29** [comment] 2022-12-23 13:33
First output before gesture
`indow manager warning: Overwriting existing binding of keysym 31 with keysym 31 (keycode a).
Window manager warning: Overwriting existing binding of keysym 32 with keysym 32 (keycode b).
Window manager warning: Overwriting existing binding of keysym 33 with keysym 33 (keycode c).
Window manager warning: Overwriting existing binding of keysym 34 with keysym 34 (keycode d).
Window manager warning: Overwriting existing binding of keysym 35 with keysym 35 (keycode e).
Window manager warning: Overwriting existing binding of keysym 36 with keysym 36 (keycode f).
Window manager warning: Overwriting existing binding of keysym 38 with keysym 38 (keycode 11).
Window manager warning: Overwriting existing binding of keysym 37 with keysym 37 (keycode 10).
Window manager warning: Overwriting existing binding of keysym 39 with keysym 39 (keycode 12).
../glib/gobject/gsignal.c:2772: instance '0x55a8507eed20' has no handler with id '254921'`

**Comment by Neo-29** [comment] 2022-12-23 13:35
Second input after gesture
`Window manager warning: Overwriting existing binding of keysym 38 with keysym 38 (keycode 11).
Window manager warning: Overwriting existing binding of keysym 31 with keysym 31 (keycode a).
Window manager warning: Overwriting existing binding of keysym 32 with keysym 32 (keycode b).
Window manager warning: Overwriting existing binding of keysym 33 with keysym 33 (keycode c).
Window manager warning: Overwriting existing binding of keysym 34 with keysym 34 (keycode d).
Window manager warning: Overwriting existing binding of keysym 35 with keysym 35 (keycode e).
Window manager warning: Overwriting existing binding of keysym 36 with keysym 36 (keycode f).
Window manager warning: Overwriting existing binding of keysym 37 with keysym 37 (keycode 10).
Window manager warning: Overwriting existing binding of keysym 39 with keysym 39 (keycode 12).
Window manager warning: Overwriting existing binding of keysym 38 with keysym 38 (keycode 11).

**Comment by Neo-29** [comment] 2022-12-23 13:36
@harshadgavali  tks to have a look at this

**Comment by Neo-29** [comment] 2022-12-25 17:56
The only way I found is reset `dconf`
strangely it works again .....until....

**Comment by sidevesh** [comment] 2022-12-25 22:36
exactly the same behavior with my issue #141  , it started working all the time a while back and after the updates @Neo-29 mentioned, it regressed back to stop working after extension disable and reenable.
@Neo-29 can you detail exactly how you are resetting dconf to get it to work again ?

**Comment by Neo-29** [comment] 2022-12-26 18:51
I `dconf reset -f / `but this result in resetting ALL gnome desktop including settings
But...
I give you a way to backup an restore .
Look down belowThis is gold mine.... 

https://ostechnix.com/backup-and-restore-linux-desktop-system-settings-with-dconf/
